name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
      - run: dart pub global activate melos
      - run: melos bootstrap
      - run: melos run analyze
